spring.datasource.url=jdbc:mysql://localhost:3306/booking_system
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# remove the dialect warning


server.port=8080

# security logging for debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.io.swagger=DEBUG

server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always



spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

booking.reservation.max-duration-hours=2
booking.reservation.min-duration-hours=1


# Gmail SMTP configuration
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mistrzxdjp@gmail.com
spring.mail.password=ltvpzsuvvvxnwzcl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# reminder hours before reservation
booking.reminder.hours-before=24

logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# JWT configuration
jwt.secret = 80c083913f28dab39e4b120704d518a6823297b6aa26c0344ca17d3aa2d5631a
# 30 minutes in millisecond
jwt.expiration=1800000
