package com.booking.system.v1.entity;

public enum AuditAction {

    USER_REGISTERED,
    USER_BLOCKED,
    USER_ACTIVATED,
    USER_DELETED,
    RESERVATION_CREATED,
    RESERVATION_CANCELLED,
    RESERVATION_RESCHEDULED,
    RESOURCE_CREATED,
    RESOURCE_DEACTIVATED,
    RESOURCE_ACTIVATED,
    RESOURCE_UPDATED,
    RESOURCE_DELETED,
    PASSWORD_CHANGED,


}
