package entity;

public enum AuditAction {

    USER_REGISTERED,
    USER_BLOCKED,
    USER_ACTIVATED,
    RESERVATION_CREATED,
    RESERVATION_CANCELLED,
    RESERVATION_RESCHEDULED,
    RESOURCE_CREATED,
    RESOURCE_DEACTIVATED,
    RESOURCE_ACTIVATED,
    PASSWORD_CHANGED

}
